version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing ...
        make install
  pre_build:
    commands:
      - echo formating...
        make format

      - echo linting...
        make lint
      
      - echo testing...
        make test
        
      - echo configuring AWS
      - $(aws ecr get-login --no-include-email --region us-east-1)
      
  build:
    commands:
      - echo building...
        make deploy
      
  post_build:
    commands:
      - ContainerName="yelp_review"
      - ImageURI=$IMAGEURI:latest
      - printf '[{"name":"CONTAINER_NAME","imageUri":"IMAGE_URI"}]' > imagedefinitions.json
      - sed -i -e "s|CONTAINER_NAME|$ContainerName|g" imagedefinitions.json
      - sed -i -e "s|IMAGE_URI|$ImageURI|g" imagedefinitions.json
      - cat imagedefinitions.json
      - echo Build completed on `date`

artifacts:
    files: imagedefinitions.json
