name: Python application
on: 
  [push]:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v3
      with: 
        python-version: "3.10"

    - name: Install
      run: |
        make install

    - name: Format
      run: |
        make format

    - name: Lint
      run: |
        make lint
      
    - name: Test
      run: |
        make test
    
    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1a
  
    - name: deploy
      run: |
        make deploy